-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CREATE TABLE IF NOT EXISTS app_user (
  "id" uuid PRIMARY KEY,
  "handle" text NOT NULL UNIQUE CHECK (char_length(handle) > 0),
  "display_name" text CHECK (char_length(display_name) <= 60),
  "bio" text CHECK (char_length(bio) <= 300),
  "image_url" text CHECK (char_length(image_url) <= 2048),
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS me (
  "id" uuid PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,
  "handle" text NOT NULL CHECK (char_length(handle) > 0),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('user:' || "id") STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS article (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "author_id" uuid DEFAULT auth_uid() NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "title" text NOT NULL CHECK (char_length(regexp_replace(title, '^[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+|[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+$', '', 'g')) > 0 AND char_length(title) <= 200),
  "description" text CHECK (char_length(description) <= 300),
  "body" text NOT NULL CHECK (char_length(regexp_replace(body, '^[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+|[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+$', '', 'g')) > 0),
  "tags" text CHECK (char_length(tags) <= 200),
  "cover_url" text CHECK (char_length(cover_url) <= 2048),
  "cover_credit" text CHECK (char_length(cover_credit) <= 120),
  "slug" text GENERATED ALWAYS AS (coalesce(nullif(btrim(left(regexp_replace(lower(title), '[^a-z0-9]+', '-', 'g'), 80), '-'), ''), 'article') || '-' || left(id::text, 8)) STORED UNIQUE CHECK (char_length(slug) > 0),
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "updated_at" portable_timestamp DEFAULT now() NOT NULL,
  "search" TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(description,'') || ' ' || coalesce(body,''))) STORED,
  "reading_minutes" integer GENERATED ALWAYS AS (greatest(1, ceil(coalesce(array_length(regexp_split_to_array(btrim(body), '\s+'), 1), 0) / 220.0)::int)) STORED,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS article_tag (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "article_id" uuid NOT NULL REFERENCES article(id) ON DELETE CASCADE,
  "tag" text NOT NULL CHECK (char_length(tag) > 0 AND char_length(tag) <= 40),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS comment (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "article_id" uuid NOT NULL REFERENCES article(id) ON DELETE CASCADE,
  "author_id" uuid DEFAULT auth_uid() NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "body" text NOT NULL CHECK (char_length(regexp_replace(body, '^[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+|[\s\u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]+$', '', 'g')) > 0 AND char_length(body) <= 2000),
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS favorite (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid DEFAULT auth_uid() NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "article_id" uuid NOT NULL REFERENCES article(id) ON DELETE CASCADE,
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "deleted_at" portable_timestamp,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('user:' || "user_id") STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS bookmark (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid DEFAULT auth_uid() NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "article_id" uuid NOT NULL REFERENCES article(id) ON DELETE CASCADE,
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('user:' || "user_id") STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS follow (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "follower_id" uuid DEFAULT auth_uid() NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "followed_id" uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "created_at" portable_timestamp DEFAULT now() NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('user:' || "follower_id") STORED NOT NULL,
  CHECK (follower_id <> followed_id)
);

CREATE TABLE IF NOT EXISTS favorite_count (
  "id" text PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "article_id" uuid NOT NULL,
  "mine_counted" integer NOT NULL CHECK (mine_counted >= 0 AND mine_counted <= 1),
  "total_at_read" integer NOT NULL CHECK (total_at_read >= 0),
  "as_of_txid" portable_int64,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('user:' || "user_id") STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS article_stats (
  "article_id" uuid PRIMARY KEY,
  "favorite_count" integer NOT NULL CHECK (favorite_count >= 0),
  "counted_txid" portable_int64 NOT NULL CHECK (counted_txid >= 0),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS tag_count (
  "id" text PRIMARY KEY CHECK (char_length(id) > 0),
  "article_count" integer NOT NULL CHECK (article_count >= 0),
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE TABLE IF NOT EXISTS favorite_index (
  "id" text PRIMARY KEY CHECK (char_length(id) > 0),
  "user_id" uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  "article_id" uuid NOT NULL,
  "active" boolean NOT NULL,
  "favorited_at" portable_timestamp NOT NULL,
  "txid" BIGINT DEFAULT pg_current_xact_id()::text::bigint,
  "scope_id" TEXT GENERATED ALWAYS AS ('public:') STORED NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_article_created_at ON article USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_article_author_id ON article USING btree (author_id);
CREATE INDEX IF NOT EXISTS idx_article_search ON article USING gin (search);
CREATE INDEX IF NOT EXISTS idx_article_tag_tag ON article_tag USING btree (tag);
CREATE INDEX IF NOT EXISTS idx_comment_article_id ON comment USING btree (article_id);
CREATE INDEX IF NOT EXISTS idx_favorite_article_id ON favorite USING btree (article_id);
CREATE INDEX IF NOT EXISTS idx_bookmark_article_id ON bookmark USING btree (article_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_article_tag_pair ON article_tag (article_id, tag);
CREATE UNIQUE INDEX IF NOT EXISTS uq_favorite_pair ON favorite (user_id, article_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_bookmark_pair ON bookmark (user_id, article_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_follow_pair ON follow (follower_id, followed_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_favorite_count_pair ON favorite_count (user_id, article_id);

COMMIT;
