-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CALL rls_protect('app_user');
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS app_user_app_user_select ON app_user;
CREATE POLICY app_user_app_user_select ON app_user FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS app_user_service_all ON app_user;
CREATE POLICY app_user_service_all ON app_user FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('me');
ALTER TABLE me ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS me_app_user_select ON me;
CREATE POLICY me_app_user_select ON me FOR SELECT TO app_user USING (me.id = auth_uid());
DROP POLICY IF EXISTS me_app_user_insert ON me;
CREATE POLICY me_app_user_insert ON me FOR INSERT TO app_user WITH CHECK (me.id = auth_uid());
DROP POLICY IF EXISTS me_app_user_update ON me;
CREATE POLICY me_app_user_update ON me FOR UPDATE TO app_user USING (me.id = auth_uid());
DROP POLICY IF EXISTS me_app_user_delete ON me;
CREATE POLICY me_app_user_delete ON me FOR DELETE TO app_user USING (me.id = auth_uid());
DROP POLICY IF EXISTS me_service_all ON me;
CREATE POLICY me_service_all ON me FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('article');
ALTER TABLE article ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS article_app_user_select ON article;
CREATE POLICY article_app_user_select ON article FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS article_service_all ON article;
CREATE POLICY article_service_all ON article FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('article_tag');
ALTER TABLE article_tag ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS article_tag_app_user_select ON article_tag;
CREATE POLICY article_tag_app_user_select ON article_tag FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS article_tag_service_all ON article_tag;
CREATE POLICY article_tag_service_all ON article_tag FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('comment');
ALTER TABLE comment ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS comment_app_user_select ON comment;
CREATE POLICY comment_app_user_select ON comment FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS comment_service_all ON comment;
CREATE POLICY comment_service_all ON comment FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('favorite');
ALTER TABLE favorite ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS favorite_app_user_select ON favorite;
CREATE POLICY favorite_app_user_select ON favorite FOR SELECT TO app_user USING (favorite.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_app_user_insert ON favorite;
CREATE POLICY favorite_app_user_insert ON favorite FOR INSERT TO app_user WITH CHECK (favorite.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_app_user_update ON favorite;
CREATE POLICY favorite_app_user_update ON favorite FOR UPDATE TO app_user USING (favorite.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_app_user_delete ON favorite;
CREATE POLICY favorite_app_user_delete ON favorite FOR DELETE TO app_user USING (favorite.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_service_all ON favorite;
CREATE POLICY favorite_service_all ON favorite FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('bookmark');
ALTER TABLE bookmark ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bookmark_app_user_select ON bookmark;
CREATE POLICY bookmark_app_user_select ON bookmark FOR SELECT TO app_user USING (bookmark.user_id = auth_uid());
DROP POLICY IF EXISTS bookmark_app_user_insert ON bookmark;
CREATE POLICY bookmark_app_user_insert ON bookmark FOR INSERT TO app_user WITH CHECK (bookmark.user_id = auth_uid());
DROP POLICY IF EXISTS bookmark_app_user_update ON bookmark;
CREATE POLICY bookmark_app_user_update ON bookmark FOR UPDATE TO app_user USING (bookmark.user_id = auth_uid());
DROP POLICY IF EXISTS bookmark_app_user_delete ON bookmark;
CREATE POLICY bookmark_app_user_delete ON bookmark FOR DELETE TO app_user USING (bookmark.user_id = auth_uid());
DROP POLICY IF EXISTS bookmark_service_all ON bookmark;
CREATE POLICY bookmark_service_all ON bookmark FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('follow');
ALTER TABLE follow ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS follow_app_user_select ON follow;
CREATE POLICY follow_app_user_select ON follow FOR SELECT TO app_user USING (follow.follower_id = auth_uid());
DROP POLICY IF EXISTS follow_app_user_insert ON follow;
CREATE POLICY follow_app_user_insert ON follow FOR INSERT TO app_user WITH CHECK (follow.follower_id = auth_uid());
DROP POLICY IF EXISTS follow_app_user_update ON follow;
CREATE POLICY follow_app_user_update ON follow FOR UPDATE TO app_user USING (follow.follower_id = auth_uid());
DROP POLICY IF EXISTS follow_app_user_delete ON follow;
CREATE POLICY follow_app_user_delete ON follow FOR DELETE TO app_user USING (follow.follower_id = auth_uid());
DROP POLICY IF EXISTS follow_service_all ON follow;
CREATE POLICY follow_service_all ON follow FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('favorite_count');
ALTER TABLE favorite_count ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS favorite_count_app_user_select ON favorite_count;
CREATE POLICY favorite_count_app_user_select ON favorite_count FOR SELECT TO app_user USING (favorite_count.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_count_app_user_insert ON favorite_count;
CREATE POLICY favorite_count_app_user_insert ON favorite_count FOR INSERT TO app_user WITH CHECK (favorite_count.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_count_app_user_update ON favorite_count;
CREATE POLICY favorite_count_app_user_update ON favorite_count FOR UPDATE TO app_user USING (favorite_count.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_count_app_user_delete ON favorite_count;
CREATE POLICY favorite_count_app_user_delete ON favorite_count FOR DELETE TO app_user USING (favorite_count.user_id = auth_uid());
DROP POLICY IF EXISTS favorite_count_service_all ON favorite_count;
CREATE POLICY favorite_count_service_all ON favorite_count FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('article_stats');
ALTER TABLE article_stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS article_stats_app_user_select ON article_stats;
CREATE POLICY article_stats_app_user_select ON article_stats FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS article_stats_service_all ON article_stats;
CREATE POLICY article_stats_service_all ON article_stats FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('tag_count');
ALTER TABLE tag_count ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tag_count_app_user_select ON tag_count;
CREATE POLICY tag_count_app_user_select ON tag_count FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS tag_count_service_all ON tag_count;
CREATE POLICY tag_count_service_all ON tag_count FOR ALL TO service USING (true) WITH CHECK (true);

CALL rls_protect('favorite_index');
ALTER TABLE favorite_index ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS favorite_index_app_user_select ON favorite_index;
CREATE POLICY favorite_index_app_user_select ON favorite_index FOR SELECT TO app_user USING (true);
DROP POLICY IF EXISTS favorite_index_service_all ON favorite_index;
CREATE POLICY favorite_index_service_all ON favorite_index FOR ALL TO service USING (true) WITH CHECK (true);

COMMIT;
