-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

CREATE OR REPLACE FUNCTION restamp_txid() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.txid := pg_current_xact_id()::text::bigint;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS restamp_txid ON app_user;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON app_user
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON me;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON me
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON article;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON article
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON article_tag;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON article_tag
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON comment;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON comment
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON favorite;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON favorite
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON bookmark;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON bookmark
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON follow;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON follow
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON favorite_count;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON favorite_count
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON article_stats;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON article_stats
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON tag_count;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON tag_count
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();
DROP TRIGGER IF EXISTS restamp_txid ON favorite_index;
CREATE TRIGGER restamp_txid BEFORE UPDATE ON favorite_index
  FOR EACH ROW EXECUTE FUNCTION restamp_txid();

COMMIT;
