-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

-- tier: container
DO $$ DECLARE t text; BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'realworld_cdc') THEN
    CREATE PUBLICATION realworld_cdc FOR TABLE app_user,article,article_tag,comment,favorite,bookmark,follow WITH (publish_generated_columns = stored);
  END IF;
  FOREACH t IN ARRAY ARRAY['app_user','article','article_tag','comment','favorite','bookmark','follow'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                   WHERE pubname = 'realworld_cdc' AND schemaname = 'public' AND tablename = t) THEN
      EXECUTE format('ALTER PUBLICATION realworld_cdc ADD TABLE %I', t);
    END IF;
  END LOOP;
END $$;
-- tier: any

-- Electric's own publication, declared rather than left to it.
-- ELECTRIC_MANUAL_TABLE_PUBLISHING makes it validate this instead of
-- building one, which is what lets its role hold only REPLICATION and
-- SELECT: creating a publication needs CREATE on the database, and
-- adding a table to one needs ownership of that table. A sync service
-- that owns the app's tables can drop them.
-- tier: container
DO $$ DECLARE t text; BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'electric_publication_default') THEN
    CREATE PUBLICATION electric_publication_default FOR TABLE app_user,me,article,article_tag,comment,favorite,bookmark,follow,favorite_count,article_stats,tag_count,favorite_index WITH (publish_generated_columns = stored);
  END IF;
  FOREACH t IN ARRAY ARRAY['app_user','me','article','article_tag','comment','favorite','bookmark','follow','favorite_count','article_stats','tag_count','favorite_index'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
                   WHERE pubname = 'electric_publication_default' AND schemaname = 'public' AND tablename = t) THEN
      EXECUTE format('ALTER PUBLICATION electric_publication_default ADD TABLE %I', t);
    END IF;
  END LOOP;
END $$;

ALTER TABLE app_user REPLICA IDENTITY FULL;
ALTER TABLE me REPLICA IDENTITY FULL;
ALTER TABLE article REPLICA IDENTITY FULL;
ALTER TABLE article_tag REPLICA IDENTITY FULL;
ALTER TABLE comment REPLICA IDENTITY FULL;
ALTER TABLE favorite REPLICA IDENTITY FULL;
ALTER TABLE bookmark REPLICA IDENTITY FULL;
ALTER TABLE follow REPLICA IDENTITY FULL;
ALTER TABLE favorite_count REPLICA IDENTITY FULL;
ALTER TABLE article_stats REPLICA IDENTITY FULL;
ALTER TABLE tag_count REPLICA IDENTITY FULL;
ALTER TABLE favorite_index REPLICA IDENTITY FULL;
-- tier: any
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon;

COMMIT;
