-- generated by pronto from program.cue — do not edit
SET lock_timeout = '5s';
SET statement_timeout = '60s';

BEGIN;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = current_user AND (rolsuper OR rolbypassrls)) THEN
    RAISE EXCEPTION 'validation triggers require a migration role that bypasses RLS (superuser or BYPASSRLS): %', current_user;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION favorite_validation_own_article(state jsonb, event jsonb) RETURNS text
LANGUAGE plv8 IMMUTABLE AS $validation$
// A reader may not favorite what they wrote. `state.rows.article` is the one
// referenced article, or empty where the reference dangles and the FK will
// refuse after this does.

const verdict = ((state, event) => state.rows.article.every((a) => a.author_id !== event.row.user_id))(state, event);
return verdict === true ? "true" : verdict === false ? "false" : "answered " + typeof verdict;
$validation$;

REVOKE EXECUTE ON FUNCTION favorite_validation_own_article(jsonb, jsonb) FROM PUBLIC;

CREATE OR REPLACE FUNCTION favorite_validate() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  items jsonb;
  event jsonb;
  v text;
BEGIN
  items := CASE WHEN TG_OP = 'UPDATE' THEN jsonb_build_array(to_jsonb(OLD)) ELSE '[]'::jsonb END;
  event := jsonb_build_object('type', lower(TG_OP), 'row', to_jsonb(NEW));
  v := favorite_validation_own_article(jsonb_build_object('items', items, 'rows', jsonb_build_object('article', (SELECT coalesce(jsonb_agg(to_jsonb(r)), '[]'::jsonb) FROM article r WHERE r."id" = NEW."article_id"))), event);
  IF v = 'false' THEN
    RAISE EXCEPTION USING ERRCODE = 'check_violation', MESSAGE = 'validation favorite.own-article';
  ELSIF v IS DISTINCT FROM 'true' THEN
    RAISE EXCEPTION USING ERRCODE = 'raise_exception', MESSAGE = 'predicate favorite.own-article ' || coalesce(v, 'answered nothing');
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS favorite_validate ON favorite;
CREATE TRIGGER favorite_validate AFTER INSERT OR UPDATE ON favorite
  FOR EACH ROW EXECUTE FUNCTION favorite_validate();

COMMIT;
