// generated by pronto from the cel: constraints in program.cue — do not edit
//
// `checks` are the SQL CHECK bodies emit.cue renders into the table DDL;
// `seed` carries what each field-level cel says about the field's own
// value, which is what vets a stated row; `enums` lists the values a
// closed constraint admits, for the readers that cannot enumerate a CUE
// disjunction, and `bounds` states what an open one admits — a range, a
// length, a pattern — for the readers that have to propose a value.
// An invariant binds `this` to the ROW, and a predicate over
// several columns constrains no single field's value, so it derives a
// CHECK body and nothing for CUE.
package realworld

import "strings"

code: state: entities: {
	AppUser: {
		checks: {
			handle: "char_length(handle) > 0"
			display_name: "char_length(display_name) <= 60"
			bio: "char_length(bio) <= 300"
			image_url: "char_length(image_url) <= 2048"
		}
		seed: [...{
			handle?: strings.MinRunes(1)
			display_name?: strings.MaxRunes(60)
			bio?: strings.MaxRunes(300)
			image_url?: strings.MaxRunes(2048)
		}]
		bounds: {
			handle: {sizeMin: 1}
			display_name: {sizeMax: 60}
			bio: {sizeMax: 300}
			image_url: {sizeMax: 2048}
		}
	}
	Me: {
		checks: {
			handle: "char_length(handle) > 0"
		}
		seed: [...{
			handle?: strings.MinRunes(1)
		}]
		bounds: {
			handle: {sizeMin: 1}
		}
	}
	Article: {
		checks: {
			title: "char_length(regexp_replace(title, '^[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+|[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+$', '', 'g')) > 0 AND char_length(title) <= 200"
			description: "char_length(description) <= 300"
			body: "char_length(regexp_replace(body, '^[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+|[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+$', '', 'g')) > 0"
			tags: "char_length(tags) <= 200"
			cover_url: "char_length(cover_url) <= 2048"
			cover_credit: "char_length(cover_credit) <= 120"
			slug: "char_length(slug) > 0"
		}
		seed: [...{
			title?: =~ "[^\\s\\v\\x{85}\\x{a0}\\x{1680}\\x{2000}-\\x{200a}\\x{2028}\\x{2029}\\x{202f}\\x{205f}\\x{3000}]" & strings.MaxRunes(200)
			description?: strings.MaxRunes(300)
			body?: =~ "[^\\s\\v\\x{85}\\x{a0}\\x{1680}\\x{2000}-\\x{200a}\\x{2028}\\x{2029}\\x{202f}\\x{205f}\\x{3000}]"
			tags?: strings.MaxRunes(200)
			cover_url?: strings.MaxRunes(2048)
			cover_credit?: strings.MaxRunes(120)
			slug?: strings.MinRunes(1)
		}]
		bounds: {
			title: {sizeMin: 1, sizeMax: 200}
			description: {sizeMax: 300}
			body: {sizeMin: 1}
			tags: {sizeMax: 200}
			cover_url: {sizeMax: 2048}
			cover_credit: {sizeMax: 120}
			slug: {sizeMin: 1}
		}
	}
	ArticleTag: {
		checks: {
			tag: "char_length(tag) > 0 AND char_length(tag) <= 40"
		}
		seed: [...{
			tag?: strings.MinRunes(1) & strings.MaxRunes(40)
		}]
		bounds: {
			tag: {sizeMin: 1, sizeMax: 40}
		}
	}
	Comment: {
		checks: {
			body: "char_length(regexp_replace(body, '^[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+|[\\s\\u0085\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000]+$', '', 'g')) > 0 AND char_length(body) <= 2000"
		}
		seed: [...{
			body?: =~ "[^\\s\\v\\x{85}\\x{a0}\\x{1680}\\x{2000}-\\x{200a}\\x{2028}\\x{2029}\\x{202f}\\x{205f}\\x{3000}]" & strings.MaxRunes(2000)
		}]
		bounds: {
			body: {sizeMin: 1, sizeMax: 2000}
		}
	}
	Follow: {
		invariant: check: "follower_id <> followed_id"
	}
	FavoriteCount: {
		checks: {
			mine_counted: "mine_counted >= 0 AND mine_counted <= 1"
			total_at_read: "total_at_read >= 0"
		}
		seed: [...{
			mine_counted?: >=0 & <=1
			total_at_read?: >=0
		}]
		bounds: {
			mine_counted: {intMin: 0, intMax: 1}
			total_at_read: {intMin: 0}
		}
	}
	ArticleStats: {
		checks: {
			favorite_count: "favorite_count >= 0"
			counted_txid: "counted_txid >= 0"
		}
		seed: [...{
			favorite_count?: >=0
			counted_txid?: >=0
		}]
		bounds: {
			favorite_count: {intMin: 0}
			counted_txid: {intMin: 0}
		}
	}
	TagCount: {
		checks: {
			id: "char_length(id) > 0"
			article_count: "article_count >= 0"
		}
		seed: [...{
			id?: strings.MinRunes(1)
			article_count?: >=0
		}]
		bounds: {
			id: {sizeMin: 1}
			article_count: {intMin: 0}
		}
	}
	FavoriteIndex: {
		checks: {
			id: "char_length(id) > 0"
		}
		seed: [...{
			id?: strings.MinRunes(1)
		}]
		bounds: {
			id: {sizeMin: 1}
		}
	}
}
