// generated by pronto from the validations in program.cue — do not edit
//
// `edges` are the reads both seats make, resolved from the schema's refs;
// `module` is the Jessie source split at its completion for the plv8 body.
package realworld

code: state: entities: {
	Favorite: validations: {
		"own-article": {
			edges: [{table: "article", key: "id", from: "article_id"}]
			module: {statements: "// A reader may not favorite what they wrote. `state.rows.article` is the one\n// referenced article, or empty where the reference dangles and the FK will\n// refuse after this does.\n", completion: "(state, event) => state.rows.article.every((a) => a.author_id !== event.row.user_id)"}
		}
	}
}
